---
- name: Install and configure PostgreSQL
  hosts: ec2_servers
  become: true
  vars:
    postgresql_db: example_db
    postgresql_user: OSCAR
    postgresql_password: secure_password  # Замените на реальный пароль

  tasks:
    - name: Install PostgreSQL
      apt:
        name: postgresql
        state: present
        update_cache: yes

    - name: Ensure PostgreSQL is running
      systemd:
        name: postgresql
        state: started
        enabled: yes

    - name: Set up PostgreSQL user
      become_user: postgres
      postgresql_user:
        name: "{{ postgresql_user }}"
        password: "{{ postgresql_password }}"
        state: present

    - name: Create PostgreSQL database
      become_user: postgres
      postgresql_db:
        name: "{{ postgresql_db }}"
        owner: "{{ postgresql_user }}"
        state: present
